# Generated by Django 3.1 on 2020-08-30 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('recurrence_freq', models.IntegerField(choices=[(1, 'Weekly'), (2, 'Biweekly'), (3, 'Monthly'), (4, 'Twice A Month'), (0, 'Once')])),
                ('importance', models.IntegerField(choices=[(1, 'Necessity'), (2, 'Basic Comfort'), (3, 'Extravagance')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('recurrence_freq', models.IntegerField(choices=[(1, 'Weekly'), (2, 'Biweekly'), (3, 'Monthly'), (4, 'Twice A Month'), (0, 'Once')])),
                ('income_name', models.CharField(max_length=100)),
                ('certainty', models.IntegerField(choices=[(1, 'Certain'), (2, 'Estimated'), (3, 'Probable')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeToAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.income')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetExpenseToAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('budget_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetexpense')),
            ],
        ),
        migrations.AddField(
            model_name='budgetexpense',
            name='expense_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.expensetype'),
        ),
        migrations.AddField(
            model_name='budgetexpense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
