# Generated by Django 3.1 on 2020-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetexpense',
            name='expense_name',
            field=models.CharField(default='default expense name', max_length=150),
            preserve_default=False,
        ),
    ]
