# Generated by Django 3.1 on 2020-09-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetexpense_expense_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetexpense',
            name='bussiness_days_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income',
            name='bussiness_days_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budgetexpense',
            name='recurrence_freq',
            field=models.IntegerField(choices=[(1, 'Weekly'), (2, 'Biweekly'), (3, 'Monthly'), (4, 'Twice A Month'), (0, 'Once'), (5, 'Annually')]),
        ),
        migrations.AlterField(
            model_name='income',
            name='recurrence_freq',
            field=models.IntegerField(choices=[(1, 'Weekly'), (2, 'Biweekly'), (3, 'Monthly'), (4, 'Twice A Month'), (0, 'Once'), (5, 'Annually')]),
        ),
    ]
