# Generated by Django 3.1 on 2020-08-30 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=30)),
                ('interest_rate', models.DecimalField(decimal_places=5, max_digits=15)),
                ('compound_periods_per_year', models.IntegerField(help_text='Use -1 to represent continuous interest')),
                ('account_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_to_balance', models.DecimalField(decimal_places=2, max_digits=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.accounttype'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
